language: python
python:
  - "3.8"

services:
  - redis-server

env:
  global:
  - DATABASE_URI: "redis://localhost:6379"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: redis-cli ping

script:
  - nosetests --with-spec --spec-color --with-coverage

# after_success:
#   - codecov
